services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: always
    environment:
      TOKEN: MY_TOKEN
    volumes:
      - ./data:/mount/dir  # for persistent JSON storage (optional)
